base_url = "https://faresbakhit.github.io/"
output_dir = "docs"
compile_sass = true
minify_html = false
gemerate_feed = true

[markdown]
highlight_code = true
highlight_theme = "cheerfully-light"
render_emoji = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[extra]
